GET http://127.0.0.1:8189/market/ws/products.wsdl

###

DELETE http://127.0.0.1:8189/market/ws/id

###

PUT http://127.0.0.1:8189/market/ws/id
Content-Type: text/xml

###

POST http://127.0.0.1:8189/market/ws
Content-Type: text/xml

<soapenv:Envelope
        xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:c="http://www.geekbrains.com/spring/ws/products">
    <soapenv:Header/>
    <soapenv:Body>
        <c:getProductRequest>
            <c:id>1</c:id>
        </c:getProductRequest>
    </soapenv:Body>
</soapenv:Envelope>

###

POST http://127.0.0.1:8189/market/ws
Content-Type: text/xml

<soapenv:Envelope
        xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:c="http://www.geekbrains.com/spring/ws/products">
    <soapenv:Header/>
    <soapenv:Body>
        <c:getProductsRequest>
            <c:any>Nothing</c:any>
        </c:getProductsRequest>
    </soapenv:Body>
</soapenv:Envelope>

###